version: '2.1'
services:
  movie-quizz-app:
    build: .
    image: movie-quizz-app
    container_name: movie-quizz-app
    environment:
      - PYTHONUNBUFFERED=1
      - API_ACCESS_TOKEN=${API_ACCESS_TOKEN}
    ports:
      - 5000:8000

  movie-quizz-app-e2e:
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile 
    image: movie-quizz-app-e2e
    container_name: movie-quizz-app-e2e
    environment:
      - PYTHONUNBUFFERED=1
      - API_ACCESS_TOKEN=${API_ACCESS_TOKEN}
      - SERVICE_URL=${SERVICE_URL}
    ports:
      - 5001:8000
