name: Run unit tests

on:
  pull_request:
    branches:
      - dev

env:
  API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m playwright install
      - name: Start the local server
        run: |
          nohup python -m flask run --host=0.0.0.0 --port=5001 &
          sleep 5  # Allow the server some time to start
      - name: Run unit tests
        run: |
          set API_ACCESS_TOKEN=${{ env.API_ACCESS_TOKEN }}
          coverage run -m pytest  -v -s
      - name: Run e2e tests
        run: |
          pytest tests/e2e --maxfail=1 --disable-warnings -q
      - name: Generate Coverage Report
        run: |
          coverage report -m
