name: Run unit tests

on:
  pull_request:
    branches:
      - dev

env:
  API_ACEESS_TOKEN: ${{ env.API_ACEESS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit tests
        run: |
          python -c "import os; "
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
